"""fix task parent/child single_parent

Revision ID: ea757376afca
Revises: b9fc1d48a108
Create Date: 2025-11-22 02:20:43.110282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea757376afca'
down_revision: Union[str, Sequence[str], None] = 'b9fc1d48a108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='taskpriority'),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='taskpriority'),
               nullable=True)
    # ### end Alembic commands ###
